//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoMVCEF.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class EntidadHospital : DbContext
    {
        public EntidadHospital()
            : base("name=EntidadHospital")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EMP> EMP { get; set; }
        public virtual DbSet<DEPT> DEPT { get; set; }
        public virtual DbSet<ENFERMO> ENFERMO { get; set; }
    
        public virtual int ELIMINARENFERMO(Nullable<int> iNSCRIPCION)
        {
            var iNSCRIPCIONParameter = iNSCRIPCION.HasValue ?
                new ObjectParameter("INSCRIPCION", iNSCRIPCION) :
                new ObjectParameter("INSCRIPCION", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ELIMINARENFERMO", iNSCRIPCIONParameter);
        }
    
        public virtual ObjectResult<ENFERMO> MOSTRARENFERMOS()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ENFERMO>("MOSTRARENFERMOS");
        }
    
        public virtual ObjectResult<ENFERMO> MOSTRARENFERMOS(MergeOption mergeOption)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ENFERMO>("MOSTRARENFERMOS", mergeOption);
        }
    }
}
